services:
  - type: web
    name: edificando-web-api
    env: java
    plan: free
    # Comando para construir tu proyecto
    buildCommand: ./mvnw clean package -DskipTests
    # Comando para iniciar tu aplicaci√≥n
    startCommand: java -jar target/edificando-web-api-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:SPRING_DATASOURCE_URL=jdbc:mysql://edificando-web-db.ctaq2o8swjil.us-east-2.rds.amazonaws.com:3306/edificando_db?useSSL\=false&allowPublicKeyRetrieval\=true&serverTimezone\=UTC
      - key: SPRING_DATASOURCE_USERNAME
        value: admin
      - key: SPRING_DATASOURCE_PASSWORD
        value: edificando2025
